### ISSUE TITLE
question: when to use jobber or scheduler?

### ISSUE THREAD

**Issue by deblauwetom** [BlackMATov/promise.hpp#18]
What is the difference in purpose, it seems you can do similar things with both?

By the way: awesome library, really nice!!

**Comment by BlackMATov** [comment]
**jobber.hpp**
The main purpose of the jobber is async executing some tasks in different threads (like a thread pool does).

**scheduler.hpp**
Tasks in scheduler are executed in a single thread (main UI thread or rendering thread for example). Also, these deferred tasks are executed manually from the preferred thread (scheduler::process_all_tasks/process_one_task etc.)

> awesome library, really nice!!

Thank you! :-)
